name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
  - type: checkboxes
    attributes:
      label: Is there any exisitng issue for this?
      description: Please search to see if there is an existing issue for this bug.
      options:
        - label: I have searched the exisitng issues
          required: true
  - type: textarea
    attributes:
      label: Current Behaviour
      description: A clear and concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Please provide the following information.
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anyhting else?
      description: |
        Add any other context about the problem here.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging your files onto this box.
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Microsoft Edge